# config.toml

[column_order]
columns = ["Ser. No.", "Reg. No.", "Name"] # DO NOT change this

[additional_columns]
columns = ["TU", "Total", "Mean", "Recommendation"]

[input_folder]
path = "../../individual_sheets"

[output_excel]
path = "../../EMT4_2_2023.xlsx"

[course_patterns]
E022 = "^E022-01-\\d+/\\d{4}$" # Mechatronic Engineering 
E023 = "^E023-\\d+-\\d+/\\d{4}$"
# Add more patterns for other courses if needed